name: Update _worker.js

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日的午夜12点运行
  workflow_dispatch:  # 手动触发

jobs:
  fetch_content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run Python script to fetch content
      run: python .github/workflows/_worker.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _worker.js
        git add ProxyIP.txt
        git commit -m "Update _worker" --allow-empty
        git push
